spring.application.name=blog-api
spring.data.mongodb.uri=mongodb://localhost:27017/blog_db
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=DEBUG
